<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <IsPackable>false</IsPackable>
    <AssemblyName>TaskbarIconSplitter.Native.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TaskbarIconSplitter.Native\TaskbarIconSplitter.Native.csproj" />
  </ItemGroup>
</Project>
